### ISSUE TITLE
Call to undefined function Bolt\Collection\is_iterable()

### ISSUE THREAD

**Issue by tomas-zemres** [bolt/collection#32]
I try to install bolt CMS, but it raises error:
```
$ composer create-project bolt/composer-install:^3.4 testapp --prefer-dist

 Do you want to use Bolt's standard folder structure? (yes/no) [yes]:
 > yes

 Would you like to enable the default site Bundle? (yes/no) [yes]:
 > yes

PHP Fatal error:  Uncaught Error: Call to undefined function Bolt\Collection\is_iterable() in /home/test/testapp/vendor/bolt/collection/src/Arr.php:67
Stack trace:
#0 /home/test/testapp/vendor/bolt/collection/src/Bag.php(127): Bolt\Collection\Arr::fromRecursive(Array)
#1 /home/test/testapp/vendor/bolt/bolt/src/Composer/Script/BundleConfigurator.php(97): Bolt\Collection\Bag->toArrayRecursive()
#2 /home/test/testapp/vendor/bolt/bolt/src/Composer/Script/BundleConfigurator.php(71): Bolt\Composer\Script\BundleConfigurator->save(Object(Bolt\Collection\MutableBag))
#3 /home/test/testapp/vendor/bolt/bolt/src/Composer/ScriptHandler.php(80): Bolt\Composer\Script\BundleConfigurator->run()
#4 phar:///usr/local/Cellar/composer/1.5.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(282): Bolt\Composer\ScriptHandler::configureProject(Object(Composer\Script\Event))
#5 phar:///usr/local/Cellar/composer/1.5.2/libexec/composer.phar/src/Composer/EventDispatcher/Even in /home/test/testapp/vendor/bolt/collection/src/Arr.php on line 67

$ php --version
PHP 7.0.25 (cli) (built: Oct 27 2017 12:55:48) ( NTS )

composer --version
Composer version 1.5.2 2017-09-11 16:59:25
```

**Comment by GwendolenLynch** [comment]
For some reason, the `symfony/polyfill-php71` package doesn't look to have installed

**Comment by tomas-zemres** [comment]
vendor contains symfony/polyfill-php71
```
$ ls -d1 vendor/symfony/polyfill-php*
vendor/symfony/polyfill-php54
vendor/symfony/polyfill-php55
vendor/symfony/polyfill-php56
vendor/symfony/polyfill-php70
vendor/symfony/polyfill-php71
```

**Comment by GwendolenLynch** [comment]
OK, I'm a bit further down this rabbit hole now.

What I know is that the Composer PHAR is not autoloading the [`"files"` section](https://github.com/symfony/polyfill-php71/blob/v1.6.0/composer.json#L23) of the polyfill … or probably any of the packages using `files`

**Comment by GwendolenLynch** [comment]
We'll tag a new release today. Thanks for the report! :+1:
